/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* CAPP_CPROBE ( int ) */
#if defined STAP_SDT_V1
#define CAPP_CPROBE_ENABLED() __builtin_expect (Cprobe_semaphore, 0)
#define Capp_Cprobe_semaphore Cprobe_semaphore
#else
#define CAPP_CPROBE_ENABLED() __builtin_expect (Capp_Cprobe_semaphore, 0)
#endif
__extension__ extern unsigned short Capp_Cprobe_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define CAPP_CPROBE(arg1) \
DTRACE_PROBE1 (Capp, Cprobe, arg1)

